wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.31
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.5
    t:
      1:
      - 1
      4: 3.9.5
      5: 0.10.31
      8:
      - 5
lr:
  desc: null
  value: 0.1
n_epochs:
  desc: null
  value: 30
plot_results:
  desc: null
  value: true
run_name:
  desc: null
  value: wandb_test
use_wandb:
  desc: null
  value: true
